not-pre: "&c你没有权限这样做"
msg:
  #ban人指令/xban 玩家名 封禁理由 <时间 0 = 永久,单位:秒,默认: 0>
  xban:
    player: "请输入要封禁的玩家"
    not-online: "玩家不在线或不存在"
    not-number: "时间参数只能是数字"
    reason: "请输入封禁理由"
    me: "请不要封禁自己"
    success: "&6对玩家 &e{0} &6实施封禁,时长: &e{1}&6 ,原因: &e{2}"
  #解ban指令/xunban 玩家名
  xunban:
    player: "请输入要解禁的玩家"
    me: "无法操作自己"
    success: "&6已对玩家 &e{0} &6实施解封"
  
  
  #当玩家解封后的第一次上线发送的信息
  unlock: 
  - "&7[&6系统&7] &e您的账户已经解封,请珍惜您的账户,不要再违反服务器规则!!!"
    
  #当时间为0时,显示的文本
  never: "永久"
  ban-msg-list:
  - '&c你已被管理员封禁!!!'
  - ''
  - '&6封禁原因:'
  - '&c{reason}'
  - '&6封禁时长: &c{time}'
  - ''
  - '&6请珍惜您的账户'
  
  
log:
  xban: "使用xban,目标玩家: {0} uuid: {1},封禁时间: {2},操作玩家: {3} uuid: {4}"
  xunban: "使用xunban,目标玩家: {0} uuid: {1},操作玩家: {2} uuid: {3}"